/**
 * Wildhaven — species catalogue.
 *
 * Sixteen animals spanning every biome, each with the data the welfare model,
 * economy and 3D world need. Colours are deliberately naturalistic so the
 * low-poly meshes read as real creatures rather than toys.
 */

import type { SpeciesDef } from "./types";

export const SPECIES: SpeciesDef[] = [
  {
    id: "lion",
    name: "African Lion",
    scientificName: "Panthera leo",
    biome: "savanna",
    icon: "🦁",
    color: "#c99a5b",
    size: "large",
    cost: 12000,
    appeal: 46,
    spaceNeeded: 250,
    preferredTemp: [22, 38],
    preferredHumidity: [20, 45],
    socialMin: 2,
    socialMax: 6,
    enrichmentNeeds: ["scent", "ball", "log"],
    diet: "carnivore",
    foodCostPerDay: 85,
    description:
      "The only truly social cat, lions live in prides and rule the open savanna. Guests adore a dozing pride at golden hour.",
    conservationStatus: "VU",
  },
  {
    id: "elephant",
    name: "African Elephant",
    scientificName: "Loxodonta africana",
    biome: "savanna",
    icon: "🐘",
    color: "#8b8781",
    size: "huge",
    cost: 24000,
    appeal: 60,
    spaceNeeded: 600,
    preferredTemp: [20, 36],
    preferredHumidity: [25, 55],
    socialMin: 3,
    socialMax: 10,
    enrichmentNeeds: ["pool", "log", "scent"],
    diet: "herbivore",
    foodCostPerDay: 160,
    description:
      "The largest land animal, endlessly intelligent and deeply familial. A herd needs vast space and a good wallow.",
    conservationStatus: "EN",
  },
  {
    id: "giraffe",
    name: "Reticulated Giraffe",
    scientificName: "Giraffa reticulata",
    biome: "savanna",
    icon: "🦒",
    color: "#d7a95a",
    size: "huge",
    cost: 18000,
    appeal: 52,
    spaceNeeded: 450,
    preferredTemp: [20, 36],
    preferredHumidity: [20, 45],
    socialMin: 3,
    socialMax: 12,
    enrichmentNeeds: ["log", "scent"],
    diet: "herbivore",
    foodCostPerDay: 120,
    description:
      "Towering browsers with hypnotic patterning. High feeders keep them reaching, just as they would in the wild.",
    conservationStatus: "EN",
  },
  {
    id: "zebra",
    name: "Plains Zebra",
    scientificName: "Equus quagga",
    biome: "savanna",
    icon: "🦓",
    color: "#e9e6df",
    size: "medium",
    cost: 7000,
    appeal: 32,
    spaceNeeded: 200,
    preferredTemp: [18, 34],
    preferredHumidity: [20, 50],
    socialMin: 4,
    socialMax: 16,
    enrichmentNeeds: ["scent", "ball"],
    diet: "herbivore",
    foodCostPerDay: 55,
    description:
      "No two stripe patterns are alike. Zebra are happiest in a bustling harem, always alert for movement.",
    conservationStatus: "NT",
  },
  {
    id: "hippo",
    name: "Common Hippopotamus",
    scientificName: "Hippopotamus amphibius",
    biome: "wetland",
    icon: "🦛",
    color: "#9a7f83",
    size: "large",
    cost: 15000,
    appeal: 44,
    spaceNeeded: 320,
    preferredTemp: [22, 34],
    preferredHumidity: [55, 90],
    socialMin: 2,
    socialMax: 8,
    enrichmentNeeds: ["pool", "scent"],
    diet: "herbivore",
    foodCostPerDay: 110,
    description:
      "Surprisingly fast and famously grumpy, hippos spend the day submerged. A deep pool is non-negotiable.",
    conservationStatus: "VU",
  },
  {
    id: "flamingo",
    name: "Greater Flamingo",
    scientificName: "Phoenicopterus roseus",
    biome: "wetland",
    icon: "🦩",
    color: "#e88fa6",
    size: "small",
    cost: 3200,
    appeal: 34,
    spaceNeeded: 40,
    preferredTemp: [18, 32],
    preferredHumidity: [55, 85],
    socialMin: 8,
    socialMax: 40,
    enrichmentNeeds: ["pool"],
    diet: "omnivore",
    foodCostPerDay: 18,
    description:
      "Pink from the shrimp they sieve, flamingos need a big, noisy flock to breed and truly thrive.",
    conservationStatus: "LC",
  },
  {
    id: "red-panda",
    name: "Red Panda",
    scientificName: "Ailurus fulgens",
    biome: "forest",
    icon: "🦊",
    color: "#b5522e",
    size: "small",
    cost: 8500,
    appeal: 48,
    spaceNeeded: 60,
    preferredTemp: [8, 24],
    preferredHumidity: [50, 80],
    socialMin: 1,
    socialMax: 2,
    enrichmentNeeds: ["climb", "scent"],
    diet: "herbivore",
    foodCostPerDay: 24,
    description:
      "A bamboo-loving acrobat of the Himalayan cloud forest. Give it tall branches and cool shade.",
    conservationStatus: "EN",
  },
  {
    id: "giant-panda",
    name: "Giant Panda",
    scientificName: "Ailuropoda melanoleuca",
    biome: "forest",
    icon: "🐼",
    color: "#f2f0eb",
    size: "large",
    cost: 26000,
    appeal: 64,
    spaceNeeded: 220,
    preferredTemp: [8, 26],
    preferredHumidity: [55, 85],
    socialMin: 1,
    socialMax: 2,
    enrichmentNeeds: ["climb", "log", "scent"],
    diet: "herbivore",
    foodCostPerDay: 130,
    description:
      "A conservation icon that eats bamboo for fourteen hours a day. The single biggest draw any park can offer.",
    conservationStatus: "VU",
  },
  {
    id: "tiger",
    name: "Bengal Tiger",
    scientificName: "Panthera tigris tigris",
    biome: "forest",
    icon: "🐯",
    color: "#d98a3d",
    size: "large",
    cost: 16000,
    appeal: 54,
    spaceNeeded: 240,
    preferredTemp: [16, 32],
    preferredHumidity: [50, 85],
    socialMin: 1,
    socialMax: 1,
    enrichmentNeeds: ["pool", "scent", "log", "ball"],
    diet: "carnivore",
    foodCostPerDay: 95,
    description:
      "A solitary striped ghost of the jungle. Tigers love to swim — a shaded pool keeps them content.",
    conservationStatus: "EN",
  },
  {
    id: "capuchin",
    name: "Capuchin Monkey",
    scientificName: "Cebus capucinus",
    biome: "forest",
    icon: "🐒",
    color: "#7c5a3a",
    size: "small",
    cost: 5200,
    appeal: 38,
    spaceNeeded: 70,
    preferredTemp: [18, 30],
    preferredHumidity: [55, 85],
    socialMin: 4,
    socialMax: 18,
    enrichmentNeeds: ["climb", "ball", "log"],
    diet: "omnivore",
    foodCostPerDay: 30,
    description:
      "Famously clever tool-users. A troop needs a jungle gym of ropes and branches to stay stimulated.",
    conservationStatus: "LC",
  },
  {
    id: "penguin",
    name: "King Penguin",
    scientificName: "Aptenodytes patagonicus",
    biome: "arctic",
    icon: "🐧",
    color: "#2f3b45",
    size: "small",
    cost: 4200,
    appeal: 42,
    spaceNeeded: 45,
    preferredTemp: [-6, 10],
    preferredHumidity: [55, 85],
    socialMin: 6,
    socialMax: 30,
    enrichmentNeeds: ["pool"],
    diet: "carnivore",
    foodCostPerDay: 26,
    description:
      "Dapper divers of the sub-Antarctic. A chilled pool and a big colony make for a joyful, waddling crowd-pleaser.",
    conservationStatus: "LC",
  },
  {
    id: "polar-bear",
    name: "Polar Bear",
    scientificName: "Ursus maritimus",
    biome: "arctic",
    icon: "🐻‍❄️",
    color: "#eef2f4",
    size: "large",
    cost: 20000,
    appeal: 56,
    spaceNeeded: 400,
    preferredTemp: [-15, 8],
    preferredHumidity: [40, 75],
    socialMin: 1,
    socialMax: 2,
    enrichmentNeeds: ["pool", "ball", "scent"],
    diet: "carnivore",
    foodCostPerDay: 140,
    description:
      "The Arctic's apex hunter. It needs deep cold water to swim and a great deal of enrichment to fend off boredom.",
    conservationStatus: "VU",
  },
  {
    id: "gray-wolf",
    name: "Gray Wolf",
    scientificName: "Canis lupus",
    biome: "mountain",
    icon: "🐺",
    color: "#8f8c88",
    size: "medium",
    cost: 6800,
    appeal: 36,
    spaceNeeded: 180,
    preferredTemp: [-10, 22],
    preferredHumidity: [30, 65],
    socialMin: 3,
    socialMax: 10,
    enrichmentNeeds: ["scent", "log"],
    diet: "carnivore",
    foodCostPerDay: 60,
    description:
      "A tightly bonded pack hunter. Wolves are unhappy alone and need room to roam and patrol.",
    conservationStatus: "LC",
  },
  {
    id: "snow-leopard",
    name: "Snow Leopard",
    scientificName: "Panthera uncia",
    biome: "mountain",
    icon: "🐆",
    color: "#cfd3d6",
    size: "medium",
    cost: 17000,
    appeal: 55,
    spaceNeeded: 220,
    preferredTemp: [-12, 18],
    preferredHumidity: [25, 55],
    socialMin: 1,
    socialMax: 2,
    enrichmentNeeds: ["climb", "scent", "log"],
    diet: "carnivore",
    foodCostPerDay: 80,
    description:
      "The ghost of the mountains, exquisitely camouflaged. It craves rocky heights to perch and survey its domain.",
    conservationStatus: "VU",
  },
  {
    id: "meerkat",
    name: "Meerkat",
    scientificName: "Suricata suricatta",
    biome: "desert",
    icon: "🦫",
    color: "#c2a878",
    size: "small",
    cost: 2600,
    appeal: 40,
    spaceNeeded: 35,
    preferredTemp: [22, 40],
    preferredHumidity: [10, 35],
    socialMin: 4,
    socialMax: 20,
    enrichmentNeeds: ["scent", "nest"],
    diet: "omnivore",
    foodCostPerDay: 14,
    description:
      "Endlessly watchful sentries of the Kalahari. A busy mob of meerkats is pure entertainment for guests.",
    conservationStatus: "LC",
  },
  {
    id: "camel",
    name: "Bactrian Camel",
    scientificName: "Camelus bactrianus",
    biome: "desert",
    icon: "🐫",
    color: "#b58c56",
    size: "large",
    cost: 6000,
    appeal: 30,
    spaceNeeded: 260,
    preferredTemp: [10, 42],
    preferredHumidity: [10, 40],
    socialMin: 2,
    socialMax: 8,
    enrichmentNeeds: ["scent", "log"],
    diet: "herbivore",
    foodCostPerDay: 50,
    description:
      "Two humps of stored fat carry it across the Gobi. Hardy and gentle, it tolerates the harshest, driest yards.",
    conservationStatus: "CR",
  },
];

/** Fast lookup by species id. */
export const SPECIES_BY_ID: Record<string, SpeciesDef> = Object.fromEntries(
  SPECIES.map((s) => [s.id, s]),
);

/** Look up a species definition by id (may be undefined). */
export function getSpecies(id: string): SpeciesDef | undefined {
  return SPECIES_BY_ID[id];
}

/** All species belonging to a given biome. */
export function speciesByBiome(biome: SpeciesDef["biome"]): SpeciesDef[] {
  return SPECIES.filter((s) => s.biome === biome);
}
